# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '1-Score' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 1-Score

  target '1-ScoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '1-ScoreUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'DropDown'
  pod 'SwiftyJSON'
  pod 'SwipeCellKit'
end
